<?php

/**
*
*/
function pp_btw2017_uu_cron_init() {
}


/**
* Menu for this module
* @return array An array with this module's settings.
*/
function pp_btw2017_uu_cron_menu() {
}


/**
* Display help and module information.
* @param path
*   Which path of the site we're displaying help.
* @param arg
*   Array that holds the current path as would be returned from arg() function.
* @return
*   help text for the path.
*/
function pp_btw2017_uu_cron_help($path, $arg) {
  $output = '';
  switch ($path) {
    case "admin/help#pp_btw2017_uu_cron":
      $output = '<p>'. t("Lädt periodisch die Daten der Sammelbalken aus dem Wiki und stellt sie als JSON bereit").'</p>';
      break;
  }
  return $output;
} // function pp_btw2017_uu_cron_help


/**
* Valid permissions for this module
* @return array An array of valid permissions for the pp_hessen module
*/
#function pp_btw2017_uu_cron_perm() {
#  return array('administer pp_btw2017_uu_cron');
#} // function pp_btw2017_uu_cron_perm()


/**
*
*/
function pp_btw2017_uu_cron_cron() {
	// vars
		$wiki = "https://wiki.piratenpartei.de";
		$pool = array(
					"liste"	=> array(
									"wiki"  => "HE:Wahlen_2017/UU",
									"title" => "Landesliste",
									"uu"    => "https://wiki.piratenpartei.de/wiki/images/5/52/BTW17_HE_Formblatt_Unterstuetzungsunterschrift.pdf",
					),

					/* Waldeck-Frankenberg */
					/*167 => array(
									"wiki"  => "HE:Wahlen_2017/UU/167",
									"title" => "Wahlkreis 167 - Waldeck",
									"uu"    => "http://wiki.piratenpartei.de/Benutzer:MiB303",
					),/**/

					/* Kassel */
					168 => array(
									"wiki"  => "HE:Wahlen_2017/UU/168",
									"title" => "Wahlkreis 168 - Kassel",
									"uu"    => "https://wiki.piratenpartei.de/wiki/images/7/75/BTW17_168_Formblatt_Unterstuetzungsunterschrift.pdf",
					),

					/* Werra-Meißner – Hersfeld-Rotenburg */
					/*169 => array(
									"wiki"  => "HE:Wahlen_2017/UU/169",
									"title" => "Wahlkreis 169 - Werra-Meißner – Hersfeld-Rotenburg",
									"uu"    => "http://wiki.piratenpartei.de/Benutzer:MiB303",
					),/**/

					/* Schwalm-Eder */
					/*170 => array(
									"wiki"  => "HE:Wahlen_2017/UU/170",
									"title" => "Wahlkreis 170 - Schwalm-Eder",
									"uu"    => "http://wiki.piratenpartei.de/wiki/images/c/cc/UU_LTW_HE_Wahlkreis_7.pdf",
					),/**/

					/* Marburg-Biedenkopf */
					171 => array(
									"wiki"  => "HE:Wahlen_2017/UU/171",
									"title" => "Wahlkreis 171 - Marburg",
									"uu"    => "https://wiki.piratenpartei.de/wiki/images/d/d9/BTW17_171_Formblatt_Unterstuetzungsunterschrift.pdf",
					),

					/* Lahn-Dill */
					/*172 => array(
									"wiki"  => "HE:Wahlen_2017/UU/172",
									"title" => "Wahlkreis 172 - Lahn-Dill",
									"uu"    => "https://dl.dropboxusercontent.com/u/22741570/Piraten/uu_ltw_he_2013_wk_16_lahn_dill_1.pdf",
					),/**/

					/* Gießen */
					173 => array(
									"wiki"  => "HE:Wahlen_2017/UU/173",
									"title" => "Wahlkreis 173 - Gießen",
									"uu"    => "https://wiki.piratenpartei.de/wiki/images/2/2b/BTW17_173_Formblatt_Unterstuetzungsunterschrift.pdf",
					),

					/* Fulda */
					/*174 => array(
									"wiki"  => "HE:Wahlen_2017/UU/174",
									"title" => "WWahlkreis 174 - Fulda",
									"uu"    => "https://wiki.piratenpartei.de/Datei:14_Fulda_I.pdf",
					),/**/

					/* Main-Kinzig – Wetterau II – Schotten */
					/*175 => array(
									"wiki"  => "HE:Wahlen_2017/UU/175",
									"title" => "WWahlkreis 175 - Main-Kinzig – Wetterau II – Schotten",
									"uu"    => "https://wiki.piratenpartei.de/Datei:14_Fulda_I.pdf",
					),/**/

					/* Hochtaunus */
					176 => array(
									"wiki"  => "HE:Wahlen_2017/UU/176",
									"title" => "Wahlkreis 176 - Hochtaunus",
									"uu"    => "https://wiki.piratenpartei.de/wiki/images/8/87/BTW17_176_Formblatt_Unterstuetzungsunterschrift.pdf",
					),

					/* Wetterau */
					/*177 => array(
									"wiki"  => "HE:Wahlen_2017/UU/177",
									"title" => "Wahlkreis 177 - Wetterau I",
									"uu"    => "http://wiki.piratenpartei.de/wiki/images/d/d4/Uu_ltw_he_2013_wahlkreis_25_wetterau_1.pdf",
					),/**/

					/*  Rheingau-Taunus */
					/*178 => array(
									"wiki"  => "HE:Wahlen_2017/UU/178",
									"title" => "Wahlkreis 178 - Rheingau-Taunus – Limburg",
									"uu"    => "http://wiki.piratenpartei.de/wiki/images/a/aa/Uu_ltw_he_2013_wk_28_rheingau_taunus_1_formular.pdf",
					),/**/

					/*  Wiesbaden */
					179 => array(
									"wiki"  => "HE:Wahlen_2017/UU/179",
									"title" => "Wahlkreis 179 - Wiesbaden",
									"uu"    => "https://wiki.piratenpartei.de/wiki/images/7/76/BTW17_179_Formblatt_Unterstuetzungsunterschrift.pdf",
					),

					/* Hanau */
					/*180 => array(
									"wiki"  => "HE:Wahlen_2017/UU/180",
									"title" => "Wahlkreis 180 - Hanau",
									"uu"    => "http://wiki.piratenpartei.de/wiki/images/d/d4/Uu_ltw_he_2013_wahlkreis_25_wetterau_1.pdf",
					),/**/

					/*  Main-Taunus */
					/*181 => array(
									"wiki"  => "HE:Wahlen_2017/UU/181",
									"title" => "Wahlkreis 181 - Main-Taunus",
									"uu"    => "http://wiki.piratenpartei.de/wiki/images/7/7d/UU_Wahl_Guth_und_Kysel.pdf",
					),/**/

					/* Frankfurt */
					182 => array(
									"wiki"  => "HE:Wahlen_2017/UU/182",
									"title" => "Wahlkreis 182 - Frankfurt am Main I",
									"uu"    => "https://wiki.piratenpartei.de/wiki/images/6/63/BTW17_182_Formblatt_Unterstuetzungsunterschrift.pdf",
					),
					183 => array(
									"wiki"  => "HE:Wahlen_2017/UU/183",
									"title" => "Wahlkreis 183 - Frankfurt am Main II",
									"uu"    => "https://wiki.piratenpartei.de/wiki/images/b/b1/BTW17_183_Formblatt_Unterstuetzungsunterschrift.pdf",
					),

					/* Groß-Gerau */
					184 => array(
									"wiki"  => "HE:Wahlen_2017/UU/184",
									"title" => "Wahlkreis 184 - Groß-Gerau",
									"uu"    => "https://wiki.piratenpartei.de/wiki/images/3/36/BTW17_184_Formblatt_Unterstuetzungsunterschrift.pdf",
					),

					/* Offenbach */
					185 => array(
									"wiki"  => "HE:Wahlen_2017/UU/185",
									"title" => "Wahlkreis 185 - Offenbach",
									"uu"    => "https://wiki.piratenpartei.de/wiki/images/7/7b/BTW17_185_Formblatt_Unterstuetzungsunterschrift.pdf",
					),

					/* Darmstadt */
					/*186 => array(
									"wiki"  => "HE:Wahlen_2017/UU/186",
									"title" => "Wahlkreis 186 - Darmstadt",
									"uu"    => "http://wiki.piratenpartei.de/wiki/images/7/7d/UU_Wahl_Guth_und_Kysel.pdf",
					),/**/

					/* Odenwald */
					/*187 => array(
									"wiki"  => "HE:Wahlen_2017/UU/187",
									"title" => "Wahlkreis 187 - Odenwald",
									"uu"    => "http://wiki.piratenpartei.de/wiki/images/7/7d/UU_Wahl_Guth_und_Kysel.pdf",
					),/**/

					/* Bergstraße */
					/*188 => array(
									"wiki"  => "HE:Wahlen_2017/UU/188",
									"title" => "Wahlkreis 188 - Bergstraße",
									"uu"    => "http://wiki.piratenpartei.de/wiki/images/7/7d/UU_Wahl_Guth_und_Kysel.pdf",
					),/**/
		);

	// find sammelbalken
		echo "start: pp_btw2017_uu_cron\n";
		$url = $wiki."/wiki/index.php?title=XXX&action=edit";
		foreach($pool as $idx => $row) {
			// load wiki source code
				$curl	= str_replace("XXX", $row["wiki"], $url);
				echo "\t".$curl."\n";

				$ch		= curl_init();
				curl_setopt($ch, CURLOPT_URL,				$curl);
				curl_setopt($ch, CURLOPT_HEADER,			0);
				curl_setopt($ch, CURLOPT_RETURNTRANSFER,	1);
				curl_setopt($ch, CURLOPT_FOLLOWLOCATION,	1);
				$data = curl_exec($ch);
				curl_close($ch);
				#print_r($data);

			// extract textarea
				preg_match_all("/<textarea[^>]*>(.*)?<\/textarea/si", $data, $regs);
				#print_r($regs);
				$data2 = $regs[1][0];
				#$data2 = utf8_decode($data2);
				#print_r($data2);

			// extract infos
				$info = array();
				preg_match_all("/\|\s*Titel\s*\=\s*(.*)?\s*\|/i", $data2, $regs2);
				#print_r($regs2);
				foreach($regs2[1] as $id => $reg) {
					$info[$id]["title"] = $reg;
					$info[$id]["title"] = str_replace("_", " ", $info[$id]["title"]);
					$info[$id]["title"] = explode("(akt", $info[$id]["title"]);
					$info[$id]["title"] = $info[$id]["title"][0];
					$info[$id]["title"] = trim($info[$id]["title"]);
				}

				preg_match_all("/\|\s*ZuSammeln\s*\=\s*(.*)?\s*/i", $data2, $regs2);
				#print_r($regs2);
				foreach($regs2[1] as $id => $reg) {
					$info[$id]["max"] = intval($reg);
				}
				if (!isset($info[$id]["max"])) {
					print_r($data);
					print_r($regs);
					print_r($data2);
					print_r($regs2);
					$info[$id]["max"] = 1;
				}

				preg_match_all("/\|\s*Gesammelt\s*\=\s*(.*)?\s*/i", $data2, $regs2);
				#print_r($regs2);
				foreach($regs2[1] as $id => $reg) {
					$info[$id]["current"] = intval($reg);
				}
				if (!isset($info[$id]["current"])) {
					print_r($data);
					print_r($regs);
					print_r($data2);
					print_r($regs2);
					$info[$id]["current"] = 0;
				}

				preg_match_all("/\|\s*OK\s*\=\s*(.*)?\s*/i", $data2, $regs2);
				#print_r($regs2);
				foreach($regs2[1] as $id => $reg) {
					$info[$id]["save"] = intval($reg);
				}
				if (!isset($info[$id]["save"])) {
					print_r($data);
					print_r($regs);
					print_r($regs2);
					$info[$id]["save"] = 0;
				}

			// add info
				#print_r($info);
				if (sizeof($info) == 1) {
					// one url = one sammelbalken
					$pool[$idx]["info"] = $info[0];
				} else {
					// more than one sammelbalken
					foreach($info as $data3) {
						// check for wahlkreis match
						if (preg_match("/wk\s*".$idx."/i", $data3["title"])) {
							$pool[$idx]["info"] = $data3;
						}
					}
				}

			// clear wiki
				unset($pool[$idx]["wiki"]);
		}
		#print_r($pool);

	// write json
		$time = time();
		$json = array(
					"rendered"	=> date("d.m.Y H:i:s", $time),
					"data"      => $pool,
		);
		$content = json_encode($json);
		$last_modified = gmdate("D, d M Y H:i:s", $time);
		$etag = md5($content);

		$maxage = 60*30; // seconds * minutes
		$expires = gmdate("D, d M Y H:i:s", $time+$maxage);


		$php = file_get_contents(drupal_get_path('module', 'pp_btw2017_uu_cron')."/btw2017_uu_json.php.txt");
		$php = str_replace("@@content@@", $content, $php);
		$php = str_replace("@@last-modified@@", $last_modified, $php);
		$php = str_replace("@@etag@@", $etag, $php);
		$php = str_replace("@@time@@", $time, $php);
		$php = str_replace("@@maxage@@", $maxage, $php);
		$php = str_replace("@@expires@@", $expires, $php);

		file_put_contents(realpath('.'.base_path()).'/btw2017_uu_json.php', $php);

	// end
		echo "end: pp_btw2017_uu_cron\n";
}

?>